name: Keep Streak Alive

on:
  schedule:
    # Run every day at 17:30 UTC = 12:00 AM Myanmar time
    - cron: "30 17 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Make commit
        run: |
          echo "Last run $(date)" > streak.txt
          git add streak.txt
          git comm
